# Generated by Django 4.0 on 2021-12-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0002_alumno_maestro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestro',
            name='apellidos',
            field=models.CharField(max_length=40),
        ),
    ]
