# Generated by Django 4.0 on 2021-12-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0003_alter_maestro_apellidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Maestro',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellidos',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(max_length=40),
        ),
    ]
