# Generated by Django 4.0 on 2021-12-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPagina', '0004_sexo_delete_maestro_alter_alumno_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=40)),
                ('titulo', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('Lic', 'Licenciatura'), ('Mae', 'Maestría'), ('Doc', 'Doctorado')], max_length=40)),
            ],
        ),
    ]
